routes/web.php
<?php

use App\Http\Controllers\BackendController;
use App\Http\Controllers\BloodRequestController;
use App\Http\Controllers\ChangePasswordController;
use App\Http\Controllers\DonorController;
use App\Http\Controllers\EventController;
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\PDFController;
use App\Http\Controllers\SuperAdminController;
use App\Models\BloodRequest;
use App\Models\Event;
use App\Models\Role;
use App\Models\User;
use Barryvdh\Debugbar\DataCollector\EventCollector;
use Illuminate\Routing\RouteRegistrar;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/')->group(function () {
    Route::controller(FrontendController::class)->group(function () {
        Route::get('/', 'index')->name('welcome');;
        Route::get('/events', 'events')->name('events');
        Route::get('/events/{id}','eventsView')->name('guest-events.view');
    });
    Route::get('/about-us', function () {
        return view('about');
    })->name('about');
    
    Route::get('/terms-conditions', function () {
        return view('terms');
    })->name('terms');

    Route::get('/privacy-policy', function () {
        return view('privacy');
    })->name('privacy');

    Route::get('/contact-us', function () {
        return view('contact');
    })->name('contact');

    Route::get('/blood-req', [FrontendController::class, 'bloodRequestCreate'])->name('bloodreq-user');
    Route::post('/blood-req', [FrontendController::class, 'bloodRequestStore'])->name('bloodreq-user-store');
});



Route::prefix('dashboard')->middleware(['auth','verified'])->group(function () {
    
    Route::controller(BackendController::class)->group(function () {
        Route::get('/', 'index')->name('dashboard');
    });
    //download pdf
    
    Route::controller(PDFController::class)->group(function () {
        Route::get('/pdfs/seeker-profile/{id}','seekerProfile')->name('seekerprofile');
        Route::get('/pdfs/last-month-report','monthReport')->name('lastmonthpdf');
        Route::get('/pdfs/last-year-report','yearReport')->name('lastyearpdf');
        Route::get('/pdfs/total-report','totalReport')->name('totalpdf');
        Route::get('/pdfs/my-report','myDonation')->name('mydonationpdf');

    });
    //managing admin add routes
    Route::controller(SuperAdminController::class)->group(function () {
        Route::get('/add-admins','userList')->name('userlist');
        Route::get('/add-admins/{id}/make-admin','makeAdmin')->name('makeadmin');
        Route::get('/add-admins/{id}/remove-admin','removeAdmin')->name('removeadmin');
        Route::get('/add-admins/{id}/make-superadmin','makeSuperAdmin')->name('makesuperadmin');
        Route::get('/add-admins/{id}/remove-superadmin','removeSuperAdmin')->name('removesuperadmin');
    });
    
    //managing profile settings routes
    Route::get('/myprofile',[DonorController::class,'profile'])->name('profile');
    Route::get('/myprofile/donation-status',[DonorController::class,'makeActive'])->name('donationStatusChange');
    Route::post('/myprofile/update',[DonorController::class,'update'])->name('profile.update');
    Route::post('/myprofile/donation',[DonorController::class,'donationStore'])->name('donation.update');
    Route::post('/myprofile/change-password',[ChangePasswordController::class,'store'])->name('change.password');
    
    Route::get('/events/req/pending',[EventController::class,'eventsPending'])->name('dashboard.events.pending');
    Route::get('/events/req/accept/{id}',[EventController::class,'approve'])->name('event-request-accept');
    Route::get('/events/req/decline/{id}',[EventController::class,'decline'])->name('event-request-decline');
    Route::get('/donor-req',[DonorController::class, 'pendingDonorsRequest'])->name('donor-request');
    Route::get('/donor-req/approve/{id}',[DonorController::class, 'acceptDonors'])->name('donor-request-accept');
    
    Route::patch('/donor-req/{id}/decline',[DonorController::class, 'rejectDonors'])->name('donor-request-decline');

    Route::get('/active-donor', [DonorController::class, 'activeDonors'])->name('active-donor');

    Route::controller(DonorController::class)->prefix('/donor/blood')->group(function () {
        Route::get('/all','list')->name('donor.list');
        Route::get('/donation-history','donationHistory')->name('donorhistory');
        Route::get('/events-histories','eventHistory')->name('eventhistory');
        Route::get('/requests', 'index')->name('donor-blood-reqs');
        Route::get('/requests/{id}/accept', 'accept')->name('donor-req-accept');
        Route::get('/requests/{id}/donated', 'donated')->name('donor-req-donated');
        Route::post('/requests/{id}/not-donated', 'notDonated')->name('donor-req-notdonated');
    });

    Route::controller(BloodRequestController::class)->group(function () {
        Route::get('/blood-req/not-approved', 'pending')->name('request.notApproved');
        Route::get('/blood-req/approve/{id}', 'approve')->name('blood-approve');
        Route::patch('/blood-req/reject/{id}', 'reject')->name('blood-reject');
        Route::get('/blood-req/assign/{bloodRequest}', 'assignIndex')->name('request-assign');
        Route::post('/blood-req/assign-donor/{bloodRequest}', 'assignDonor')->name('donor-assign');
        Route::get('/blood-req-all', 'allRequests')->name('blood-request-all');
        Route::get('/blood-req', 'create')->name('blood-req');
        Route::post('/blood-req', 'store')->name('blood-store');
        Route::get('/blood-req/{id}', 'show')->name('blood-view');
        Route::get('/blood-req/{id}/edit', 'edit')->name('blood-edit');
        Route::Patch('/blood-req/{bloodRequest}/update', 'update')->name('blood-update');
    });

   
    Route::get('/events-trash', [EventController::class, 'trash'])->name('events.trash');
    Route::resource('events', EventController::class);
});











require __DIR__ . '/auth.php';

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use App\Models\BloodRequest;
use App\Models\Event;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class BackendController extends Controller
{
    private function donor()
    {
        $role_id = 3;
        if (Auth::user()->role_id == $role_id) {
            return true;
        } else {
            return false;
        }
    }
    protected function protect()
    {
        if ($this->donor()) {
            abort(404);
        };
    }
   
    public function index()
    {   
        
        $donationAvail = Carbon::parse(Carbon::now()->subMonths(3));

        $eventRequests = Event::whereNull('status')->count();
        $signupRequests = User::whereNull('approval_status')->whereNull('rejected_by')->count();

        $availableDonors = User::whereNull('last_donated')->orWhereDate('last_donated', '<=', $donationAvail)
                        ->count();  
        // dd($availableDonors)  ;


        $bloodRequests = BloodRequest::whereNull('approved_by')->whereNull('status')->whereNull('rejected_by')->count();
        $totalDonors = User::count();
          
        // dd($totalDonors);
        $ongoing = Auth::user()->bloodRequests()->wherePivot('status',1)->first();
        $usersBloodRequests = Auth::user()->bloodRequests()->wherePivotNull('status')->count();
        return view('backend/dashboard',compact(
        'signupRequests',
        'eventRequests',
        'usersBloodRequests',
        'ongoing',
        'bloodRequests',
        'totalDonors',
        'availableDonors'
    ));
    }
}

resources/views/backend/active-donors.blade.php
<x-backend.layouts.master>
    
    <div class="container-fluid px-4">
        <h1 class="mt-4">Active Donors List</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">
                Dashboard
            </li>
            <li class="breadcrumb-item active">
                Donors
            </li>
            <li class="breadcrumb-item active">    
                Active Donors
            </li>
        </ol>
      
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table me-1"></i>
                Active donors list
            </div>
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>DOB</th>
                            <th>BL Group</th>
                            <th>Area</th>
                            <th>Post Code</th>
                            <th>Joined at</th>
                            <th>Last donated</th>
                            <th>Action</th>
                        </tr> 
                    </thead>
                    <tbody>
                        <tr>
                            <td>Tiger Nixon</td>
                            <td>12-12-12</td>
                            <td>O+</td>
                            <td>Dhaka</td>
                            <td>1430</td>
                            <td>2011/04/25</td>
                            <td>4months ago</td>
                            <td class="d-flex"> 
                                
                                <a href="" title="view" class="btn btn-info btn-sm" style="color: white" ><i class="fa-solid fa-eye"></i></a> 
                                
                                
                                
                                <a href="" title="make not ready" class="btn btn-danger btn-sm" style="margin-left: 3px" ><i class="fas fa-toggle-off"></i></a> 
                             
                        </tr>
                     
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</x-backend.layouts.master>

resources/views/backend/dashboard.blade.php
<x-backend.layouts.master>
  
    @if ($ongoing)
        <marquee width="max-width:250px" style="background-color: bisque"> <a href="{{route('donor-blood-reqs')}}">!!You have a ongoing donation activity!!</a> </marquee>
    @endif


    <div class="container-fluid px-4">
        <h1 class="mt-4">Dashboard</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
        </ol>

        @if (auth()->user()->isAdmin() ||
            auth()->user()->isSuperAdmin())
            <div class="row">
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-primary text-white mb-4">
                        <div class="card-body">
                            <p>Blood request Pending</p>
                            <span>{{$bloodRequests ?? "No requests"}}</span>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="{{route('request.notApproved')}}">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-warning text-white mb-4">
                        <div class="card-body">
                            <p>Donor Signup Request</p>
                            <span>{{$signupRequests}}</span>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="{{route('donor-request')}}">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-success text-white mb-4">
                        <div class="card-body">
                            <p>Event Upload request</p>
                            
                            <span>{{$eventRequests}}</span>
                        </div>
                        <div class="card-footer d-flex align-items-center justify-content-between">
                            <a class="small text-white stretched-link" href="{{ route('dashboard.events.pending') }}">View Details</a>
                            <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-md-6">
                    <div class="card bg-danger text-white mb-4">
                        <div class="card-body">
                            <p class="text-center my-0 fw-bold">{{ date('Y-m-d') }}</p>
                            <table>
                                <tbody>
                                    <tr>
                                        <td>Total Donors</td>
                                        <td>:</td>
                                        <td>{{$totalDonors}}</td>
                                    </tr>
                                    <tr>
                                        <td>Available Donors</td>
                                        <td>:</td>
                                        <td>{{$availableDonors}}</td>
                                    </tr>
                                    <tr>
                                        <td>Blood Seekers</td>
                                        <td>:</td>
                                        <td>{{$bloodRequests}}</td>
                                    </tr>


                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>
        @endif



        <div class="row">
            <legend>Your Notifications</legend>
            <div class="col-xl-3 col-md-6">
                <div class="card text-white mb-4" style="background-color: rgb(157, 105, 28)">
                    <div class="card-body">
                        <p>Blood Request</p>
                        <span>{{ $usersBloodRequests ?? 'No requests' }}</span>
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small text-white stretched-link" href="{{ route('donor-blood-reqs') }}">View
                            Details</a>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
            <div class="col-xl-3 col-md-6">
                <div class="card text-white mb-4" style="background-color:coral">
                    <div class="card-body">
                        <p>Your events</p>
                        <span>0</span>
                    </div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small text-white stretched-link" href="{{route('eventhistory')}}">View Details</a>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>

        </div>
        

    </div>


    <script src="{{asset('backend/js/bootstrap.bundle.min')}}" crossorigin="anonymous"></script>

   

</x-backend.layouts.master>

resources/views/backend/event-edit.blade.php
<x-backend.layouts.master>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Events</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
            <li class="breadcrumb-item active">Events</li>
            <li class="breadcrumb-item active">Edit</li>
        </ol>
        <x-utilities.form.errors/>
        <x-utilities.form.success/>
        <!-- form-group // -->

    </div>


    <div class="card mb-4">
        <div class="card-header">

            <div class="row">
                <div class="col-9">
                    <i class="fas fa-table me-1"></i>
                    Edit
                </div>
                <div class="col-3">
                    <a href="{{ route('events.index') }}" class="btn btn-outline-primary" role="button">Event
                        List</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('events.update',$event->id) }}" method="POST" enctype="multipart/form-data">
                @csrf
                <!-- 2 column grid layout with text inputs for the first and last names -->
                <div class="row mb-4">
                    <div class="col">
                        <div class="form-outline">
                            <input type="text" id="form6Example1" class="form-control" name="title"
                                value="{{ old('title',$event->title) }}" />
                            <label class="form-label" for="form6Example1">Event title</label>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-outline">
                            <input type="date" id="form6Example5" class="form-control" name="event_date"
                                value="{{ old('event_date',$event->event_date) }}" />
                            <label class="form-label" for="form6Example5">Event's date:</label>
                        </div>
                    </div>
                </div>

                <!-- Text input -->


                <!-- Text input -->


                <!-- Email input -->
                <div class="form-outline mb-4">
                    <div class="row mb-4">
                        <div class="col">
                            <input type="text" id="form6Example2" class="form-control"  name="area" value="{{old('area',$event->area)}}" />
                            <label class="form-label" for="form6Example2">Area</label>

                        </div>
                        <div class="col">
                            <div class="form-outline mb-4">
                                <input type="text" id="form6Example6" class="form-control" name="organized_by"
                                    value="{{ old('organized_by',$event->organized_by) }}" />
                                <label class="form-label" for="form6Example6">Organized by:</label>
                            </div>

                        </div>

                    </div>

                </div>

                <!-- Number input -->


                <!-- Message input -->
                <div class="form-outline mb-4">
                    <textarea class="form-control" id="mytextarea" name="description" rows="4">{{ old('description',$event->description) }}</textarea>
                    <label class="form-label" for="mytextarea">Description</label>
                </div>

                <!-- Checkbox -->
                <div class="form-outline mb-4">
                    <label class="form-label" for="customFile">Select a image:</label>
                    <input type="file" class="form-control" id="customFile" name="image"
                        value="{{ old('image',$event->image) }}" />
                </div>

                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4 w-100">Update</button>


            </form>
        </div>
    </div>
    </div>
</div>

    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
</x-backend.layouts.master>

resources/views/backend/event-show.blade.php
<x-backend.layouts.master>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Events</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
            <li class="breadcrumb-item active">Events</li>
            <li class="breadcrumb-item active">{{$event->title}}</li>
        </ol>

        

    </div>


    <div class="card mb-4">
        <div class="card-header">
            <div class="row">
                <div class="col-9">
                    <i class="fas fa-table me-1"></i>
                    {{$event->title}}
                </div>
                <div class="col-3">
                    <a href="{{ route('events.edit', $event->id) }}" class="btn btn-outline-primary" role="button">Edit</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <div class="container pt-2 px-5">
                <div class="row">
                  <div class="col-md-4 ms-5">
                    <p><b>Area: Uttara, Dhaka-1230</b></p>
                  </div>
                  <div class="col-md-3 ms-5">
                   <p><b>Date: 19 Mar,2022</b></p>
                 </div>
                 <div class="col-md-3 ms-5">
                   <p><b>Posted By: Nur Islam</b></p>
                 </div>
                </div>
               </div>
               <hr>
             </section>
             <section>
               <div class="container  h-100">
                  <div class="row p-0  justify-content-center align-items-center h-100" style="width: 100%">
                      <div class="col-12 col-md-8 col-lg-6 col-xl-8 p-0" style="width: 100%">
                        <div class="card-body p-5 ">   
                         <div class="mb-md-5 md-4 pb-5"> 
                          <h1 class="lead" style="text-align: center;">Events</h1> <hr>
                          
                            <div >
                              <form action="">
                                <img src="{{asset('storage/events/'.$event->image)}}" alt="" width="100%" height="350px">
                                <div> <br>
                                <h4>{{$event->title}}</h4>
                                </div>
                               
                               <div class="">
                               <hr>
                                 <p style="text-align: justify;">  {{$event->description}}</p>
                               </div>
                              
                              </form>
       
       
       
                            </div>
                         
                         </div>
                        </div>
                      </div> 
                   </div>
               </div><br>
        </div>
    </div>
    </div>
</div>


</x-backend.layouts.master>

resources/views/backend/events-create.blade.php
<x-backend.layouts.master>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Events</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
            <li class="breadcrumb-item active">Events</li>
            <li class="breadcrumb-item active">Create</li>
        </ol>
        @if (session('message'))
            <p class="alert alert-success">{{ session('message') }}</p>
        @endif
        <!-- form-group // -->
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

    </div>


    <div class="card mb-4">
        <div class="card-header">

            <div class="row">
                <div class="col-9">
                    <i class="fas fa-table me-1"></i>
                    Create a event
                </div>
                <div class="col-3">
                    <a href="{{ route('events.index') }}" class="btn btn-outline-primary" role="button">Event
                        List</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('events.store') }}" method="POST" enctype="multipart/form-data">
                @csrf

                <!-- 2 column grid layout with text inputs for the first and last names -->
                <div class="row mb-4">
                    <div class="col">
                        <div class="form-outline">
                            <input type="text" id="form6Example1" class="form-control" name="title"
                                value="{{ old('title') }}" />
                            <label class="form-label" for="form6Example1">Event title</label>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-outline">
                            <input type="date" id="form6Example5" class="form-control" name="event_date"
                                value="{{ old('event_date') }}" />
                            <label class="form-label" for="form6Example5">Event's date:</label>
                        </div>
                    </div>
                </div>

                <!-- Text input -->


                <!-- Text input -->


                <!-- Email input -->
                <div class="form-outline mb-4">
                    <div class="row mb-4">
                        <div class="col">
                            <input type="text" id="form6Example2" class="form-control"  name="area" value="{{old('area')}}" />
                            <label class="form-label" for="form6Example2">Area</label>

                        </div>
                        <div class="col">
                            <div class="form-outline mb-4">
                                <input type="text" id="form6Example6" class="form-control" name="organized_by"
                                    value="{{ old('organized_by') }}" />
                                <label class="form-label" for="form6Example6">Organized by:</label>
                            </div>

                        </div>

                    </div>

                </div>

                <!-- Number input -->


                <!-- Message input -->
                <div class="form-outline mb-4">
                    <textarea class="form-control" id="mytextarea" name="description" rows="4">{{ old('description') }}</textarea>
                    <label class="form-label" for="mytextarea">Description</label>
                </div>

                <!-- Checkbox -->
                <div class="form-outline mb-4">
                    <label class="form-label" for="customFile">Select a image:</label>
                    <input type="file" class="form-control" id="customFile" name="image"
                        value="{{ old('image') }}" />
                </div>

                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4">Upload Event</button>


            </form>
        </div>
    </div>
    </div>
</div>

    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
</x-backend.layouts.master>

resources/views/backend/events.blade.php
<x-backend.layouts.master>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Events</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Dashboard</li>
            <li class="breadcrumb-item active">Events</li>
        </ol>

        <div class="card mb-4">
            <div class="card-header">

                <div class="row">
                    <div class="col-9">
                        <i class="fas fa-table me-1"></i>
                        Events list
                    </div>
                    <div class="col-3">
                        <a href="{{ route('events.create') }}" class="btn btn-outline-primary" role="button">Add new
                            Event</a>
                        <a href="" class="btn btn-outline-dark" role="button">Trash</a>
                    </div>
                </div>
            </div>
            @if (session('message'))
                <p class="alert alert-success">{{ session('message') }}</p>
            @endif
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="card-body">
                <table id="datatablesSimple">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Image</th>
                            <th>Title</th>
                            <th>Description</th>
                            <th>Organized By</th>
                            <th>Uploaded_by</th>
                            <th>Approved_by</th>
                            <th>Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($events as $event)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $event->image }}</td>
                                <td>{{ $event->title }}</td>
                                <td>{{ Str::limit($event->description, 20, '...') }}</td>
                                <td>{{ $event->organized_by }}</td>
                                <td>{{ $event->uploadedBy->name }}</td>
                                <td>{{ $event->approvedBy->name }}</td>

                                <td class="d-flex">
                                    <a href="{{ route('events.show', $event->id) }}" role="button"
                                        class="btn btn-primary btn-sm">Show</a>
                                    <a href="" role="button" class="btn btn-info btn-sm">Edit</a>
                                    <form action="{{ route('events.destroy', $event->id) }}">
                                        @csrf

                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>

                                    </form>

                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>





</x-backend.layouts.master>